# Generated by Django 5.2.8 on 2025-11-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
